import React, {useEffect, useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowRight, BookOpen, Brain, Check, ChevronRight, Clock, Facebook, Globe2, GraduationCap, Heart, Instagram, Languages, Linkedin, Mail, MapPin, Menu, Monitor, Phone, Search, Sparkles, Star, Users, X, Youtube} from 'lucide-react';
import './styles.css';
import logo from './assets/logo.png';
import hero from './assets/hero.jpg';
import mission from './assets/mission.jpg';
import why from './assets/why.jpg';
import teach from './assets/teach.jpg';
import seerah from './assets/seerah.jpg';
import nazra from './assets/nazra.jpg';
import arabic from './assets/arabic.jpg';
import sqa from './assets/sqa.jpg';
import data from './assets/data.jpg';
import kids from './assets/kids.jpg';
import abdullah from './assets/abdullah.jpg';
import safaa from './assets/safaa.webp';
import philosophy from './assets/philosophy.png';
import craft from './assets/craft.png';
import influence from './assets/influence.png';
import sponsor from './assets/sponsor.webp';
import seerat from './assets/seerat.jpg';
import islamiat from './assets/islamiat.jpg';
import urdu from './assets/urdu.jpg';
import eesha from './assets/eesha.png';
import eesha2 from './assets/eesha2.jpg';

const courses = [
 {id:'223', title:'Seerah & Case Studies', age:'Ages 15–23', category:'Islamic Studies', level:'Advanced', duration:'12 months', lesson:'60 min', price:'5,999', image:seerah, featured:true, description:'A reflective, thematic study of the life of the Prophet ﷺ that connects divine guidance with leadership, character and everyday choices.'},
 {id:'221', title:'Nazra Quran Majeed', category:'Quran', level:'Beginner', duration:'6 months', lesson:'50 min', price:'5,999', image:nazra, featured:true, description:'Develop confident, correct Quranic recitation through guided practice in Tajweed, Makharij, pronunciation and fluency.'},
 {id:'208', title:'Arabic for Professionals', category:'Arabic Language', level:'Beginner', duration:'18 months', lesson:'50 min', price:'2,999', image:arabic, featured:true, description:'Build practical Arabic for the workplace, academic settings, professional dialogue, presentations and confident communication.'},
 {id:'292', title:'Software Quality Assurance', category:'STEM', level:'Beginner', duration:'4 months', lesson:'40 min', price:'1,000', image:sqa, description:'Learn manual testing, test-case design, bug reporting and essential quality-assurance tools through hands-on projects.'},
 {id:'291', title:'Data Science Foundations', category:'STEM', level:'Beginner', duration:'5 months', lesson:'30 min', price:'1,000', image:data, description:'Gain practical skills in data analysis, visualization, statistics and the foundations of machine learning.'},
 {id:'224', title:'Tarbiyah for Kids', age:'Ages 7–13', category:'Tarbiyah', level:'Beginner', duration:'2 months', lesson:'60 min', price:'5,999', image:kids, description:'A nurturing journey rooted in timeless principles, helping young hearts grow in knowledge, character and spirituality.'},
 {id:'226', title:'Seerat un Nabi', category:'Islamic Studies', level:'Beginner', duration:'12 months', lesson:'60 min', price:'5,999', image:seerat, description:'Explore the Makki and Madani periods through a mission-oriented study of Prophetic character, leadership and reform.'},
 {id:'219', title:'Islamiat', category:'Islamic Studies', level:'Beginner', duration:'3 months', lesson:'40 min', price:'5,999', image:islamiat, description:'Grade-wise concept mapping, individual concept-clearing sessions and focused learning rooted in Islamic values.'},
 {id:'218', title:'Urdu', category:'Languages', level:'Beginner', duration:'3 months', lesson:'40 min', price:'5,999', image:urdu, description:'Build confident reading, writing and expression through guided, outcome-based Urdu language instruction.'}
];

const faculty = [
 {name:'Muhammad Waqas Jamil', subject:'Arabic Language', initials:'MW'},
 {name:'Qari Muhammad Asif Zubair', subject:'Quran & Tajweed', initials:'QA'},
 {name:'Abdullah Farooq', subject:'English Language', image:abdullah},
 {name:'Safaa Ali Feroze', subject:'Seerah Studies', image:safaa},
 {name:'Ahsan Gillani', subject:'Life Skills', initials:'AG'},
 {name:'Warda Umer', subject:'Character Development', initials:'WU'},
 {name:'Ammara Rauf', subject:'Life Skills', initials:'AR'},
 {name:'Eesha Ahmad', subject:'Learning Facilitator', image:eesha},
 {name:'Eesha Ahmad', subject:'Academic Support', image:eesha2},
 {name:'Janzaib Borana', subject:'Business & Life Coaching', initials:'JB'}
];

function go(path){ history.pushState({},'',path); window.dispatchEvent(new Event('routechange')); window.scrollTo({top:0,behavior:'smooth'}); }
function Link({to, children, className=''}){ return <a href={to} className={className} onClick={e=>{if(!e.metaKey&&!e.ctrlKey){e.preventDefault();go(to)}}}>{children}</a> }

function Header(){
 const [open,setOpen]=useState(false); const [path,setPath]=useState(location.pathname);
 useEffect(()=>{const f=()=>{setPath(location.pathname);setOpen(false)}; addEventListener('popstate',f);addEventListener('routechange',f);return()=>{removeEventListener('popstate',f);removeEventListener('routechange',f)}},[]);
 const nav=[['/','Home'],['/courses','Courses'],['/about-us','About'],['/faculty','Faculty'],['/become-instructor','Teach with us']];
 return <><div className="topbar"><div className="container top-inner"><span><Phone size={14}/> +92 319 730 1071</span><span className="top-right"><Mail size={14}/> tarbiyahonline@meemacademy.org <i></i> Lahore, Pakistan</span></div></div>
 <header><div className="container nav"><Link to="/" className="brand"><img src={logo}/><span><b>MEEM</b><small>ACADEMIA</small></span></Link><nav className={open?'open':''}>{nav.map(([p,n])=><Link key={p} to={p} className={(path===p || p!=='/'&&path.startsWith(p))?'active':''}>{n}</Link>)}<Link to="/courses" className="nav-cta">Explore courses <ArrowRight size={16}/></Link></nav><button className="menu" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></div></header></>
}

function Footer(){return <footer><div className="container footer-grid"><div className="foot-brand"><Link to="/" className="brand light"><img src={logo}/><span><b>MEEM</b><small>ACADEMIA</small></span></Link><p>Learning that deepens faith, develops skill and inspires meaningful contribution.</p><div className="socials"><a><Facebook/></a><a><Instagram/></a><a><Youtube/></a><a><Linkedin/></a></div></div><div><h4>Explore</h4><Link to="/courses">All courses</Link><Link to="/about-us">Our mission</Link><Link to="/faculty">Our faculty</Link><Link to="/become-instructor">Teach with us</Link></div><div><h4>Learning</h4><a>Islamic studies</a><a>Arabic language</a><a>STEM education</a><a>Student sponsorship</a></div><div><h4>Get in touch</h4><p className="contact"><MapPin/> Lahore, Pakistan</p><p className="contact"><Phone/> +92 319 730 1071</p><p className="contact"><Mail/> tarbiyahonline@meemacademy.org</p></div></div><div className="container copyright"><span>© 2026 Meem Academia. All rights reserved.</span><span>Privacy · Terms · Data deletion</span></div></footer>}

function SectionHead({eyebrow,title,text,center=false}){return <div className={'section-head '+(center?'center':'')}><span className="eyebrow">{eyebrow}</span><h2>{title}</h2>{text&&<p>{text}</p>}</div>}
function CourseCard({course}){return <article className="course-card"><Link to={'/course-details/'+course.id} className="course-img"><img src={course.image}/><span className="level">{course.level}</span>{course.featured&&<span className="featured"><Star size={13} fill="currentColor"/> Featured</span>}</Link><div className="course-body"><span className="category">{course.category}</span><Link to={'/course-details/'+course.id}><h3>{course.title} {course.age&&<small>{course.age}</small>}</h3></Link><p>{course.description}</p><div className="course-meta"><span><Clock/> {course.lesson}</span><span><BookOpen/> {course.duration}</span></div><div className="course-foot"><div><small>Starting monthly</small><strong>Rs {course.price}</strong></div><Link to={'/course-details/'+course.id} className="circle-link"><ArrowRight/></Link></div></div></article>}

function Home(){return <main>
 <section className="hero"><div className="hero-orb one"></div><div className="hero-orb two"></div><div className="container hero-grid"><div className="hero-copy"><span className="eyebrow"><Sparkles size={15}/> Learn with purpose</span><h1>Knowledge that shapes <em>who you become.</em></h1><p>Deepen your faith, strengthen your character and build future-ready skills through transformative learning—wherever you are.</p><div className="hero-actions"><Link to="/courses" className="btn primary">Explore courses <ArrowRight/></Link><Link to="/about-us" className="btn ghost">Discover our mission</Link></div><div className="trust"><div className="avatars"><span>MA</span><span>AZ</span><span>SF</span></div><div><b>Join a growing community</b><small>Learners across Pakistan and beyond</small></div></div></div><div className="hero-visual"><div className="hero-collage"><div className="image-frame"><img src={hero}/></div><div className="collage-small cs-one"><img src={seerah}/></div><div className="collage-small cs-two"><img src={kids}/></div><div className="float-card fc-one"><span><GraduationCap/></span><div><b>Live learning</b><small>Guided by experts</small></div></div><div className="float-card fc-two"><b>4.9 <Star size={15} fill="currentColor"/></b><small>Student satisfaction</small></div></div></div></div></section>
 <section className="stats"><div className="container stats-grid"><div><strong>500<span>+</span></strong><small>Active learners</small></div><div><strong>20<span>+</span></strong><small>Expert instructors</small></div><div><strong>15<span>+</span></strong><small>Purposeful courses</small></div><div><strong>95<span>%</span></strong><small>Student success</small></div></div></section>
 <section className="section"><div className="container"><SectionHead eyebrow="Featured programs" title="Explore learning that transforms" text="Carefully designed programs that unite timeless guidance with the skills learners need today."/><div className="course-grid">{courses.slice(0,3).map(c=><CourseCard course={c} key={c.id}/>)}</div><div className="center-button"><Link to="/courses" className="btn outline">View all courses <ArrowRight/></Link></div></div></section>
 <section className="section sage"><div className="container mission-grid"><div className="mission-img"><img src={mission}/><div className="quote">“The purpose of knowledge is not merely to know, but to become.”</div></div><div><SectionHead eyebrow="Our approach" title="Rooted in guidance. Ready for the world."/><p className="lead">We believe every learner carries a divine potential—to think clearly, act righteously and live purposefully.</p><div className="pillars"><div><span><img src={philosophy}/></span><div><h4>The Philosophy</h4><p>Every learner carries the potential to think clearly, act righteously and live purposefully.</p></div></div><div><span><img src={craft}/></span><div><h4>The Craft</h4><p>Authentic teaching, interactive learning and guided reflection turn knowledge into growth.</p></div></div><div><span><img src={influence}/></span><div><h4>The Influence</h4><p>The outcome is visible in the good learners carry into their homes, communities and world.</p></div></div></div><Link to="/about-us" className="text-link">Learn about our philosophy <ArrowRight/></Link></div></div></section>
 <section className="section"><div className="container"><SectionHead center eyebrow="Learning pathways" title="Grow in every dimension" text="A balanced education for the heart, mind and future."/><div className="path-grid"><div className="path-card dark"><span><BookOpen/></span><h3>Islamic Studies</h3><p>Seerah, Quran and Tarbiyah programs that connect revelation to everyday life.</p><Link to="/courses">Explore pathway <ArrowRight/></Link></div><div className="path-card gold"><span><Languages/></span><h3>Arabic Language</h3><p>Build meaningful communication—from foundations to professional fluency.</p><Link to="/courses">Explore pathway <ArrowRight/></Link></div><div className="path-card cream"><span><Monitor/></span><h3>STEM & Professional</h3><p>Practical, future-ready skills taught through projects and expert guidance.</p><Link to="/courses">Explore pathway <ArrowRight/></Link></div></div></div></section>
 <section className="visual-story"><div className="container"><div className="story-grid"><div className="story-copy"><span className="eyebrow">One connected journey</span><h2>Faith, fluency and future-ready skills.</h2><p>Every image here comes directly from Meem Academia’s current learning programs—reframed into a clearer, more confident digital experience.</p><Link to="/courses" className="text-link">See every program <ArrowRight/></Link></div><div className="story-photo tall"><img src={nazra}/><span>Quran fluency</span></div><div className="story-photo"><img src={arabic}/><span>Arabic for life</span></div><div className="story-photo"><img src={data}/><span>Future skills</span></div><div className="story-photo wide"><img src={seerah}/><span>Prophetic guidance</span></div></div></div></section>
 <section className="section sponsor-section"><div className="container sponsor-grid"><div><span className="eyebrow">Make learning accessible</span><h2>Sponsor a student. Shape a future.</h2><p>Your contribution helps a deserving learner access live classes, expert guidance and a community that believes in their potential.</p><div className="sponsor-numbers"><span><b>500+</b><small>students sponsored</small></span><span><b>95%</b><small>success rate</small></span></div><button className="btn primary">Sponsor now <Heart size={17}/></button></div><div className="sponsor-art"><img src={sponsor}/></div></div></section>
 <section className="section cta-section"><div className="container cta"><div><span className="eyebrow light-eye">Start your journey</span><h2>Learn deeply. Live purposefully.</h2><p>Join a community committed to knowledge, character and meaningful contribution.</p></div><Link to="/courses" className="btn white">Find your course <ArrowRight/></Link></div></section>
 </main>}

function Courses(){const [filter,setFilter]=useState('All');const [query,setQuery]=useState(''); const items=useMemo(()=>courses.filter(c=>(filter==='All'||c.category===filter||(filter==='STEM'&&c.category==='STEM'))&&c.title.toLowerCase().includes(query.toLowerCase())),[filter,query]);return <main><PageHero eyebrow="Our programs" title="Find the course that moves you forward" text="Explore thoughtful learning experiences in Islamic studies, language and future-ready skills."/><section className="section course-list"><div className="container"><div className="filterbar"><div className="filters">{['All','Islamic Studies','Arabic Language','STEM'].map(f=><button className={filter===f?'selected':''} onClick={()=>setFilter(f)} key={f}>{f}</button>)}</div><label className="search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search courses"/></label></div><div className="course-grid">{items.map(c=><CourseCard course={c} key={c.id}/>)}</div>{!items.length&&<div className="empty">No courses match your search.</div>}</div></section></main>}

function PageHero({eyebrow,title,text}){return <section className="page-hero"><div className="pattern"></div><div className="container"><span className="eyebrow light-eye">{eyebrow}</span><h1>{title}</h1><p>{text}</p></div></section>}

function CourseDetail({id}){const c=courses.find(x=>x.id===id)||courses[0];return <main><section className="detail-hero"><div className="container detail-grid"><div><div className="breadcrumbs"><Link to="/courses">Courses</Link><ChevronRight/> {c.category}</div><span className="eyebrow light-eye">{c.category}</span><h1>{c.title}</h1><p>{c.description}</p><div className="detail-meta"><span><Clock/> {c.lesson} sessions</span><span><BookOpen/> {c.duration}</span><span><Globe2/> English / Urdu</span></div></div><div className="detail-image"><img src={c.image}/></div></div></section><section className="section"><div className="container content-grid"><article className="prose"><SectionHead eyebrow="Course overview" title="A journey of insight and transformation"/><p>This course moves beyond information to nurture deep understanding, thoughtful reflection and practical growth. Learners explore each topic through guided discussion, relevant examples and meaningful activities.</p><h3>What you’ll learn</h3><ul className="check-list"><li><Check/>Connect foundational knowledge with real-life choices</li><li><Check/>Develop critical thinking, reflection and decision-making</li><li><Check/>Strengthen identity, character and purposeful leadership</li><li><Check/>Learn with expert guidance in an interactive environment</li></ul><h3>Learning experience</h3><p>Weekly live classes combine structured teaching, questions, group reflection and practical exercises. Recordings and learning resources help students review at their own pace.</p><div className="curriculum"><h3>Course curriculum</h3>{['Foundations & essential concepts','Guided study and real-world context','Reflection, discussion and case studies','Application, character and lasting impact'].map((x,i)=><div className="module" key={x}><span>0{i+1}</span><b>{x}</b><small>{i===0?'Getting started':'Core module'}</small><ChevronRight/></div>)}</div></article><aside className="enroll-card"><div className="enroll-top"><small>Individual plan · per month</small><h2>Rs {c.price}</h2><p>Live classes, resources and instructor support included.</p></div><button className="btn primary wide" onClick={()=>alert('Enrollment request received!')}>Reserve your spot <ArrowRight/></button><div className="includes"><b>This course includes</b><span><Check/> Weekly live sessions</span><span><Check/> Learning resources</span><span><Check/> Instructor feedback</span><span><Check/> Completion certificate</span></div><div className="help"><Phone/><div><small>Need help choosing?</small><b>+92 319 730 1071</b></div></div></aside></div></section></main>}

function About(){return <main><PageHero eyebrow="Who we are" title="Education that reconnects knowledge with purpose" text="We help learners approach divine guidance with clarity, build strong character and develop the skills to benefit the world."/><section className="section"><div className="container split"><div><img className="rounded-img" src={mission}/></div><div><SectionHead eyebrow="Our mission" title="Nurturing the next generation of excellence"/><p className="lead">Today’s world is changing quickly. In uncertainty, the guidance of the Creator remains our greatest anchor—but approaching that guidance requires knowledge, language and clarity.</p><p>Meem Academia creates that pathway through meaningful education that is intellectually satisfying, emotionally grounding and spiritually uplifting.</p><div className="mini-stats"><span><b>Global</b><small>online community</small></span><span><b>Holistic</b><small>learning model</small></span></div></div></div></section><section className="section sage"><div className="container"><SectionHead center eyebrow="Why Meem" title="Knowledge that becomes action"/><div className="values-grid">{[['01','Resetting knowledge','We make timeless principles relevant to modern life, preserving values while reviving their purpose.'],['02','Reviving eloquence','Clarity and sincerity allow beautiful ideas to speak directly to the human heart.'],['03','Meaning in struggle','Authentic perspectives bring direction and comfort through life’s difficult moments.'],['04','Reconnecting purpose','Knowledge returns to its mission: guiding humanity with wisdom and compassion.']].map(v=><div className="value" key={v[0]}><span>{v[0]}</span><h3>{v[1]}</h3><p>{v[2]}</p></div>)}</div></div></section><section className="section"><div className="container split reverse"><div><img className="rounded-img" src={why}/></div><div><SectionHead eyebrow="Our vision" title="Learners who become a source of healing, wisdom and direction"/><p className="lead">We envision a generation that lives with confidence, compassion and clarity.</p><p>When knowledge is presented with depth, relevance and care, it naturally speaks to the soul—without pressure, force or fear.</p><Link to="/courses" className="btn primary">Explore our programs <ArrowRight/></Link></div></div></section></main>}

function Faculty(){return <main><PageHero eyebrow="Meet our team" title="Guides for your learning journey" text="Experienced educators and subject specialists committed to thoughtful, personal and exceptional learning."/><section className="section"><div className="container"><SectionHead eyebrow="Our faculty" title="Learn from people who care" text="Knowledgeable mentors who combine subject expertise with empathy and character."/><div className="faculty-grid">{faculty.map(f=><div className="faculty-card" key={f.name}><div className="faculty-photo">{f.image?<img src={f.image}/>:<span>{f.initials}</span>}<div className="faculty-social"><Linkedin/></div></div><div><small>Senior Instructor</small><h3>{f.name}</h3><p>{f.subject}</p></div></div>)}</div></div></section><section className="section sage"><div className="container cta-light"><div><span className="eyebrow">Join the mission</span><h2>Have knowledge worth sharing?</h2><p>Inspire students worldwide and become part of a purposeful learning community.</p></div><Link to="/become-instructor" className="btn primary">Teach with us <ArrowRight/></Link></div></section></main>}

function Teach(){const [sent,setSent]=useState(false); return <main><section className="teach-hero"><img src={teach}/><div className="overlay"></div><div className="container"><span className="eyebrow light-eye">Make a difference</span><h1>Teach with us</h1><p>Share your expertise, inspire learners worldwide and help build a brighter future.</p></div></section><section className="section"><div className="container"><div className="benefit-grid">{[[Clock,'Flexible scheduling','Teach around your commitments with thoughtfully planned online classes.'],[Monitor,'Remote teaching','Connect with learners from anywhere through our virtual classroom.'],[Heart,'Meaningful impact','Shape knowledge, character and confidence in the next generation.']].map(([Icon,t,p])=><div className="benefit" key={t}><span><Icon/></span><h3>{t}</h3><p>{p}</p></div>)}</div></div></section><section className="section sage"><div className="container application-grid"><div><SectionHead eyebrow="Instructor application" title="Bring your expertise to Meem"/><p className="lead">We’re looking for educators who teach with clarity, sincerity and care.</p><ul className="check-list"><li><Check/>Flexible online opportunities</li><li><Check/>Supportive academic community</li><li><Check/>Purposeful, values-led work</li><li><Check/>Students from diverse backgrounds</li></ul></div>{sent?<div className="success"><span><Check/></span><h2>Application received</h2><p>Thank you for your interest. Our team will be in touch if your profile is shortlisted.</p></div>:<form className="apply-form" onSubmit={e=>{e.preventDefault();setSent(true)}}><div className="form-row"><label>First name<input required placeholder="Your first name"/></label><label>Last name<input required placeholder="Your last name"/></label></div><label>Email address<input required type="email" placeholder="you@example.com"/></label><label>Phone number<input required placeholder="+92 300 000 0000"/></label><div className="form-row"><label>Teaching area<select required defaultValue=""><option value="" disabled>Select an area</option><option>Islamic Studies</option><option>Arabic Language</option><option>STEM Education</option><option>Life Skills</option></select></label><label>Experience<select required defaultValue=""><option value="" disabled>Select experience</option><option>1–2 years</option><option>3–5 years</option><option>6+ years</option></select></label></div><label>Why would you like to teach with Meem?<textarea rows="4" placeholder="Tell us briefly about your experience and motivation"></textarea></label><button className="btn primary wide">Submit application <ArrowRight/></button></form>}</div></section></main>}

function App(){const [path,setPath]=useState(location.pathname);useEffect(()=>{const f=()=>setPath(location.pathname);addEventListener('popstate',f);addEventListener('routechange',f);return()=>{removeEventListener('popstate',f);removeEventListener('routechange',f)}},[]);let page;if(path==='/')page=<Home/>;else if(path==='/courses')page=<Courses/>;else if(path==='/about-us')page=<About/>;else if(path==='/faculty'||path==='/faculity')page=<Faculty/>;else if(path==='/become-instructor')page=<Teach/>;else if(path.startsWith('/course-details/'))page=<CourseDetail id={path.split('/').pop()}/>;else page=<Home/>;return <><Header/>{page}<Footer/></>}

createRoot(document.getElementById('root')).render(<App/>);
